# Site settings
author: Cat Price
title: A Hot Cup of Java
header-img: img/home-bg.png
email: catprice444@gmail.com
copyright_name: Cat Price
description: > # this means to ignore newlines until "baseurl:"
  My adventures in learning to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  catprice444

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
